# Generate a fake data that has 100 rows and 4 features A,B,C,D. The label y should be binary (0 or 1)

In [22]:
from sklearn.datasets import make_multilabel_classification


X, y = make_multilabel_classification(n_classes=1, 
                                      n_labels=1,
                                      n_features=4,
                                      random_state=42)

In [23]:
print(X[:5])

[[11. 15. 11. 15.]
 [ 4. 15.  8. 12.]
 [12.  6. 16. 12.]
 [ 9.  8. 11. 12.]
 [12. 10.  8. 10.]]


In [28]:
print(y[:5])

[[0]
 [0]
 [0]
 [0]
 [0]]


In [38]:
# value counts of y
import numpy as np

unique_values, counts = np.unique(y, return_counts=True)
print(unique_values)
print(counts)

[0 1]
[44 56]


In [25]:
import pandas as pd

df =pd.DataFrame(X, columns=["A", "B", "C", "D"])
df['target'] = y

print(df)

       A     B     C     D  target
0   11.0  15.0  11.0  15.0       0
1    4.0  15.0   8.0  12.0       0
2   12.0   6.0  16.0  12.0       0
3    9.0   8.0  11.0  12.0       0
4   12.0  10.0   8.0  10.0       0
..   ...   ...   ...   ...     ...
95   8.0  13.0  14.0  11.0       0
96  13.0  16.0  12.0   7.0       0
97  12.0  11.0  17.0   9.0       0
98  13.0   7.0  12.0  11.0       0
99  13.0  12.0  11.0  16.0       0

[100 rows x 5 columns]
